global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'chat-service'
    static_configs:
      - targets: ['chat-service:3002']

  - job_name: 'rest-service'
    static_configs:
      - targets: ['rest-service:3001']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']