events {
    worker_connections 1024;
}

http {
    upstream chat {
        server chat-service:3002;
    }

    upstream rest {
        server rest-service:3001;
    }

    server {
        listen 80;

        location /chat/ {
            proxy_pass http://chat;
        }

        location /api/ {
            proxy_pass http://rest;
        }
    }
}

