events {
    worker_connections 1024;
}

http {
    upstream chat {
        server chat-service:3002;
    }

    upstream rest {
        server rest-service:3001;
    }

    server {
        listen 80;

        location /chat/ {
            proxy_pass http://chat;
        }

        location /api/ {
            proxy_pass http://rest;
        }

        location /stub_status {
            stub_status;
            allow 127.0.0.1;
            allow 172.0.0.0/8;  # Permite acesso pela rede Docker
            deny all;
        }
    }
}

